Migrate Walterlv.Logger to dotnetCampus.Logger
dotnet-campus/dotnetCampus.Logger pull request #1
Opened 2020-10-04 02:43 UTC by walterlv

2020-10-04 02:44 UTC, lindexi commented on Directory.Build.props
> +    <Description>dotnetCampus.Logger is a high-performance logging tool for client apps. It also provide Markdown formatter to let your log file beautiful including output table and code. Notice: it
推荐加上一句中文 提供统一的日志记录方法，并附带各种各样的实现

2020-10-04 02:55 UTC, lindexi requested changes
文件写入的设计上推荐更改

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Composition/CompositeLogger.cs
> +        private readonly Dictionary<ILogger, ILogger> _loggers;
为什么不使用 HastSet 方法

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Composition/CompositeLogger.cs
> +        private readonly object _locker = new object();
是否可以将 _loggers 作为 lock 这样可以减少一个对象

private object Locker => _loggers;

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Core/AsyncOutputLogger.AsyncQueue.cs
> +        private class AsyncQueue<T>
比较推荐使用源代码包安装

```xml
<PackageReference Include="dotnetCampus.AsyncWorkerCollection.Source" Version="1.2.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Core/AsyncOutputLogger.AsyncQueue.cs
> +        private class AsyncQueue<T>
这个代码是古老代码，将会存在内存泄露问题

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Core/AsyncOutputLogger.cs
> +        private readonly AsyncQueue<LogContext> _queue;
这里推荐使用 DoubleBufferTask 的实现，这个实现方式支持批量给出日志

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Core/AsyncOutputLogger.cs
> +                    context = await _queue.DequeueAsync(_waitForEmptyCancellationTokenSource.Token).ConfigureAwait(false);
这里只能每次给一条日志，测试文件下载库可以了解，如果有速度很快的加入，有大量的时间都在等待锁上。而通过 DoubleBufferTask 也等待锁，但是使用的是 lock 加上不需要每一次都进入锁等待

在批量进入的时候，使用 DoubleBufferTask 的性能会比 AsyncQueue 好一点点，性能好多少取决于加入和消费的速度比

而 DoubleBufferTask 的缺点在于只能多对一，而 AsyncQueue 的设计是多对多。这里只需要使用多对一，使用 DoubleBufferTask 的效率更高

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Core/AsyncOutputLogger.cs
> +                    while (_queue.Count > 0)
使用 DoubleBufferTask  提供完全执行完成方法

2020-10-04 02:55 UTC, lindexi commented on src/dotnetCampus.Logger/Core/AsyncOutputLogger.cs
> +        protected async Task WaitFlushingAsync()
这是不对的，命名上这里只能说进入方法，而不能说文件写入文件

如果是用在控制台执行完成，此时程序退出，但是日志还没写完

2020-10-04 03:01 UTC, lindexi commented on src/dotnetCampus.Logger/ILogger.cs
> +    public interface ILogger
推荐的设计上，不要给这个接口这么多的方法，推荐的是给出一个空实现。其他的如 Trace 等方法都是扩展方法。优势在于可以满足各个业务的需求。对使用方来说几乎没差别

开放的方法建议只有一个，也就是传入值同时包含将值序列化为字符串的委托

```
void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);

void Log<TState>(TState state, Exception exception, Func<TState, Exception, string> formatter);

void Log<TState>(TState state,  Func<TState, string> formatter);
```

也就是说实际的实现是给对应的扩展方法自己实现的，因此可以做到各个项目的定制化需求的时候，是通过传入的 formatter 修改参数的

上面几个签名可选其中一个来做

我也推荐将  LogLevel 带上，这样可以做全局的配置，设置是否记录日志

2020-10-04 03:02 UTC, lindexi commented on src/dotnetCampus.Logger/ILogger.cs
> +    public interface ILogger
通过这个实现，可以添加静态类，提供默认的序列化方法

因为 TState 是可以任意类型，因此可以有不同的静态类，满足不同的需求。如我在 Core 使用的是性能要求极高的方式，而我在业务层，我使用的是性能很多的参数

2020-10-04 03:03 UTC, lindexi commented on src/dotnetCampus.Logger/dotnetCampus.Logger.csproj
> +    	<Description>提供统一的日志记录方法，并附带各种各样的实现。dotnetCampus.Logger is a high-performance logging tool for client apps. It also provide Markdown formatter to let your log file beautiful including output tab
描述加错地方了

2020-10-04 03:04 UTC, lindexi commented on src/dotnetCampus.Logger/Core/LogContext.cs
> +    public readonly struct LogContext
这个实现是不能满足所有需求的，因此需要框架提供可以传任意的日志信息类型

2020-10-04 03:05 UTC, lindexi commented on src/dotnetCampus.Logger/IO/TextFileLogger.cs
> +            _infoMutex = CreateMutex(_infoLogFile);
建议的设计是只有一个线程写入文件，这样的效率更高

如果有多个进程写入相同的问题，让业务层去处理

2020-10-04 03:07 UTC, lindexi commented on src/dotnetCampus.Logger/IO/TextFileLogger.cs
> +        protected virtual string BuildLogText(in LogContext context, bool containsExtraInfo, string lineEnd)
这里算一个设计上的不足，也就是不能让用户自定义输出的内容。如果可以让开发者通过自己注入格式化委托，如上面评论的方法，此时就可以做到定制化日志输出

2020-10-04 03:08 UTC, lindexi commented on src/dotnetCampus.Logger/IO/TextFileLogger.cs
> +            var time = context.Time.ToLocalTime().ToString("yyyy.MM.dd HH:mm:ss.fff", CultureInfo.InvariantCulture);
咱私有云的日志是 CCloudLogger 的格式化需求是 `[2099-10-19 19:07:45.456][threadName][INFO][类:行数][_traceId:realTraceId][_userId:realUserId][tag:custom] 业务的日志/异常堆栈
` 所以不建议这里给出日志的固定序列化

2020-10-04 03:10 UTC, lindexi commented on src/dotnetCampus.Logger/IO/TextFileLogger.cs
> +                        WaitFlushingAsync().Wait();
建议使用 IAsyncDisposable 接口，这个定义在 .NET Framework 没有

2020-10-04 03:10 UTC, lindexi commented on src/dotnetCampus.Logger/IO/TextFileLogger.cs
> +                mutex.WaitOne();
不推荐卡线程来写，推荐使用一个线程来写。如果有多个进程写入相同的文件，让业务层去解决

2020-10-04 03:13 UTC, lindexi commented on src/dotnetCampus.Logger/IO/TextFileLoggerExtensions.cs
> +                    File.WriteAllText(file.FullName, "");
其实推荐的是干掉日志的一半，而不是清空日志文件

2020-10-04 03:17 UTC, lindexi commented on src/dotnetCampus.Logger/LogLevel.cs
> +        None = 0x00,
序号推荐是反过来的，这样可以使用简单的大于判断

也就是如果记录的是 Info 等级的，所有传入大于 Info 等级的，都可以记录

这个只是我的习惯而已，如果你这个序号没特别含义，还期望能用我的这个方法。因为我在内部库都用了这个方法，使用的话，内部库接入简单

2020-10-04 03:18 UTC, lindexi commented on src/dotnetCampus.Logger/LogLevel.cs
> +        Message = 0x04,
建议设置为 Information 和 Debug 和 Trace 这几级

2020-10-04 03:18 UTC, lindexi commented on src/dotnetCampus.Logger/LogLevel.cs
> +        Detail = 0xf0,
不建议使用 Detail 这个命名，推荐使用 Debug 或 Trace 这几个

2020-10-04 03:20 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogFormatter.cs
> +    public static class MarkdownLogFormatter
如果之前使用的是通过扩展的方法，而不是在 Ilogger 添加记录方法。这个类写起来将会更清真，可以通过日志注入格式化委托，将传入的值进行序列化，因此可以做到在需要转换日志为字符串才调用委托

2020-10-04 03:20 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogFormatter.cs
> +        public static void TraceCode(this ILogger logger, string text, string lang, string code, [CallerMemberName] string? callerMemberName = null)
这个命名太通用，不能体现这是给 MarkdownLogFormatter 的格式使用的

2020-10-04 03:21 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogFormatter.cs
> +        public static void TraceTable<T>(this ILogger logger, string text,
这个命名太通用，不能体现这是给 MarkdownLogFormatter 的格式使用的

2020-10-04 03:21 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogFormatter.cs
> +        public static void TraceCode(this ILogger logger, string text, string lang, string code, [CallerMemberName] string? callerMemberName = null)
请问 logger.TraceCode 将会记录什么信息？其实很难猜到是 MarkdownLogFormatter  的

2020-10-04 03:22 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogFormatter.cs
> +        public static void MessageCode(this ILogger logger, string text, string lang, string code, [CallerMemberName] string? callerMemberName = null)
这个命名太通用，不能体现这是给 MarkdownLogFormatter 的格式使用的

2020-10-04 03:22 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogFormatter.cs
> +        public static void MessageTable<T>(this ILogger logger,
如果 ILogger 使用扩展方法传入格式化委托，这个类不需要这么多的方法，可以统一传入参数

2020-10-04 03:23 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogger.cs
> +                LogLevel.Fatal => $"**{context.Text}** *致命错误，异常中止*",
中文输入，建议支持配置`致命错误，异常中止`

2020-10-04 03:23 UTC, lindexi commented on src/dotnetCampus.Logger/Markdown/MarkdownLogger.cs
> +        public MarkdownLogger(FileInfo logFile, bool append, string lineEnd)
这是一个新的库，可以抛弃这两个方法

2020-10-04 03:24 UTC, lindexi commented on src/dotnetCampus.Logger/Standard/ConsoleLogWriter.cs
> +            var currentTime = DateTimeOffset.Now;
这个库有很多时间的格式化方法，推荐有统一的方式

2020-10-04 03:27 UTC, lindexi commented
设计上建议拆分为两个库，或三个

两个库的方法是：一个仅接口定义和一些静态辅助方法，用于作为所有库的基础。另一个是包含具体实现

三个库的方法是：和上面两个库的相同。同时加上第三个库包含上面两个库的代码，用于减少 dll 引用

2020-10-11 07:52 UTC, walterlv commented on src/dotnetCampus.Logger/Core/AsyncOutputLogger.cs
> +        protected async Task WaitFlushingAsync()
有同步版本的日志可以用（这库两个版本都有）

2020-10-12 00:42 UTC, lindexi commented on src/dotnetCampus.Logger/LoggerMethods.cs
> +        public static void Trace(this ILogger logger, string text, [CallerMemberName] string? callerMemberName = null)
这里的 Trace 缺少了上下文追踪的功能，这需要在 logger 类里面包含了上下文信息才能做到

2020-10-12 01:14 UTC, lindexi commented
void Log(T logContext, IFormatter formatter); 底层基础

formatter 读取出 LogLevel 和 String 等值

2024-04-26 23:53 UTC, closed without merging